spring:
  application:
    name: HelloWorldClient
  cloud:
    zookeeper:
      connect-string: localhost:2181,localhost:2182,localhost:2183
      discovery:
        enabled: true
logging:
  level:
    org.apache.zookeeper.ClientCnxn: WARN