ibm:
  mq:
    pool:
      enabled: true
    queueManager: mqdev
    connName: mqdev-efs-LoadBala-1DV8M3TLB6MBI-1870985021.ap-southeast-1.elb.amazonaws.com(1414)
    channel: PASSWORD.SVRCONN
    user: johndoe
    password: passw0rd
    #ccdtUrl: file:///Users/jerrywang/self/mycode/ng-gateway/ibmmq/src/main/resources/AMQCLCHL.TAB_219_MDEV

spring:
  jms:
    cache:
      enabled: true

logging:
  level:
    com.ibm.mq.spring.boot: TRACE

top:
  mq:
    outQueueName: Q1
    inQueueName: Q1
    tps: 10
    total: 10
    qMgrName: mqdev
    host: mqdev-efs-LoadBala-1DV8M3TLB6MBI-1870985021.ap-southeast-1.elb.amazonaws.com
    port: 1414
    channel: PASSWORD.SVRCONN
    userId: johndoe
    password: passw0rd
    appName: "Top application"
#ibm.mq.channel=SYSTEM.DEF.SVRCONN
#ibm.mq.connName=localhost(1414)

# Change the following lines as necessary. Set the ibm.mq.user
# property to an empty string to send no authentication request.
#ibm.mq.user=mqguest
# ibm.mq.user=
#ibm.mq.password=passw0rd