ibm:
  mq:
    pool:
      enabled: true
    queueManager: QMPTSMDEV
    user:
    ccdtUrl: file:///Users/jerrywang/self/mycode/ng-gateway/ibmmq/src/main/resources/AMQCLCHL.TAB_219_MDEV

spring:
  jms:
    cache:
      enabled: true

logging:
  level:
    com.ibm.mq.spring.boot: TRACE

top:
  mq:
    outQueueName: queue1
    inQueueName: queue1
    tps: 100
    total: 10
#ibm.mq.channel=SYSTEM.DEF.SVRCONN
#ibm.mq.connName=localhost(1414)

# Change the following lines as necessary. Set the ibm.mq.user
# property to an empty string to send no authentication request.
#ibm.mq.user=mqguest
# ibm.mq.user=
#ibm.mq.password=passw0rd